# Generated by Django 4.2.4 on 2023-08-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ciclo",
            fields=[
                ("modificado", models.DateTimeField(auto_created=True)),
                ("creado", models.DateTimeField(auto_created=True)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "codigo",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
