# Generated by Django 4.2.4 on 2023-08-20 23:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ciclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modificado", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auditorias.ciclo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
