# Generated by Django 4.2.4 on 2023-08-21 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auditorias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modificado", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=200)),
                ("tipo", models.CharField(max_length=20)),
                ("estado", models.CharField(max_length=20)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
